config/routes.rb
Rails.application.routes.draw do
  # Users
  devise_for :users
  get 'users/:username' => 'users#show', as: 'show_user'

  # Playlists
  resources :playlists do
    member do
      patch 'end'
      post 'add_track'
    end
  end

  resources :playlist_songs, only: [:destroy] do
    member do
      patch 'move_higher'
      patch 'move_lower'
    end
  end
  resources :songs, only: [:show]
  resources :artists, only: [:index, :show]
  resources :albums, only: [:index, :show]
  resources :labels, only: [:index, :show]

  root 'playlists#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/playlist_song.rb
class PlaylistSong < ApplicationRecord
  # relations
  belongs_to :playlist
  belongs_to :song
  # other
  acts_as_list scope: :playlist
end

app/controllers/playlist_songs_controller.rb
class PlaylistSongsController < ApplicationController
  before_action :set_playlist_song

  def edit
  end

  def move_lower
    @playlist_song.move_lower
    flash[:notice] = "Song moved."

    respond_to do |format|
      format.js { render 'playlists/update_table' }
      format.html { redirect_to @playlist_song.playlist }
    end
  end

  def move_higher
    @playlist_song.move_higher
    flash[:notice] = "Song moved."

    respond_to do |format|
      format.js { render 'playlists/update_table' }
      format.html { redirect_to @playlist_song.playlist }
    end
  end

  def destroy
    if @playlist_song.destroy
      flash[:notice] = "#{@playlist_song.song.name} removed from playlist."
    else
      flash[:alert] = "Couln't remove song from playlist."
    end

    respond_to do |format|
      format.js { render 'playlists/update_table' }
      format.html { redirect_to @playlist_song.playlist }
    end
  end

  private

  def set_playlist_song
    @playlist_song = PlaylistSong.find(params[:id])
  end
end

app/views/playlist_songs/_actions.html.erb
<%= link_to playlist_song_path(playlist_song), remote: true, method: :delete do %>
  <%= fa_icon 'eraser' %>
<% end %>

<% unless playlist_song.first? %>
  <%= link_to move_higher_playlist_song_path(playlist_song), remote: true, method: :patch do %>
    <%= fa_icon 'arrow-up'  %>
  <% end %>
<% end %>

<% unless playlist_song.last? %>
  <%= link_to move_lower_playlist_song_path(playlist_song), remote: true, method: :patch do %>
    <%= fa_icon 'arrow-down' %>
  <% end %>
<% end %>