config/routes.rb
Rails.application.routes.draw do
  # Users
  devise_for :users
  get 'users/:username' => 'users#show', as: 'show_user'

  # Playlists
  resources :playlists do
    member do
      patch 'end'
      post 'add_track'
    end
  end

  resources :playlist_songs, only: [:destroy] do
    member do
      patch 'move_higher'
      patch 'move_lower'
    end
  end
  resources :songs, only: [:show]
  resources :artists, only: [:index, :show]
  resources :albums, only: [:index, :show]
  resources :labels, only: [:index, :show]

  root 'playlists#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/playlist.rb
class Playlist < ApplicationRecord
  # relations
  belongs_to :user
  has_many :playlist_songs, -> { order(position: :asc) }
  has_many :songs, through: :playlist_songs

  # validations
  validates :name, presence: true
  validates :user, presence: true
  validates :played_at, presence: true
  validates :status, uniqueness: { scope: :user, if: :in_progress? }

  # status enum
  enum status: [:in_progress, :ended]
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  before_action :find_playlist, only: [:show, :edit, :update, :add_track, :end]
  before_action :authenticate_user!, only: [:new, :edit, :update, :create]

  def index
    @playlists = Playlist.order(created_at: :desc).includes(:user).page params[:page]
  end

  def show
  end

  def new
    if current_user.playlists.in_progress.any?
      flash[:notice] = "You cannot start a new playlist until you end your current playlist."
      redirect_to current_user.playlists.in_progress.first
    end
    @playlist = Playlist.new
  end

  def edit
    unless @playlist.user_id == current_user.id
      render text: 'UNAUTHORIZED', status: :unauthorized
    end
  end

  def create
    @playlist = Playlist.new(playlist_params.merge(user: current_user))

    if @playlist.save
      @songs = @playlist.songs
      render 'playlists/show'
    else
      render 'playlists/new'
    end
  end

  def update
    if @playlist.user_id != current_user.id
      redirect_to @playlist, notice: 'Unauthorized action'
    elsif @playlist.update(playlist_params)
      redirect_to @playlist, notice: 'Playlist was successfully updated.'
    else
      render 'playlists/edit'
    end
  end

  def add_track
    AddTrackService.new(@playlist).append(add_track_params)
    redirect_to playlist_path(@playlist)
  end

  def end
    authorize! :update, @playlist
    @playlist.ended!
    redirect_to playlists_path
  end

  private
  def add_track_params
    {
      artist_name: params[:artist_name],
      album_name: params[:album_name],
      song_name: params[:song_name],
      label_name: params[:label_name]
    }
  end

  def playlist_params
    params.require(:playlist).permit [:name, :played_at]
  end

  def find_playlist
    @playlist = Playlist.find(params[:id])
  end
end

app/views/playlists/_add_song_form.html.erb
<%= form_with url: add_song_playlist_path(id: playlist.id), autocomplete: 'off' do |f| %>
<div class='form-row'>
  <div class='col-3'>
    <%= f.label :artist_name %>
    <%= f.select :artist_name, [], {}, id: :artist_name %>
  </div>

  <div class='col-3'>
    <div class='form-group'>
      <%= f.label :song_name %>
      <%= f.text_field :song_name, id: :song_name %>
    </div>
  </div>

  <div class='col-3'>
    <div class='form-group'>
      <%= f.label :album_name %>
      <%= f.select :album_name, [], {}, id: :album_name %>
    </div>
  </div>

  <div class='col-3'>
    <div class='form-group'>
      <%= f.label :label_name %>
      <%= f.select :label_name, [], {}, id: :label_name %>
    </div>
  </div>
</div>
<div class='form-row'>
  <%= f.submit 'Add Song to Playlist', class: 'btn btn-info'%>
</div>
<% end %>

app/views/playlists/_add_track_form.html.erb
<%= form_with url: add_track_playlist_path(id: playlist.id), autocomplete: 'off' do |f| %>
<div class='form-row'>
  <div class='col-3'>
    <%= f.label :artist_name %>
    <%= f.select :artist_name, [], {}, id: :artist_name %>
  </div>

  <div class='col-3'>
    <div class='form-group'>
      <%= f.label :song_name %>
      <%= f.text_field :song_name, id: :song_name %>
    </div>
  </div>

  <div class='col-3'>
    <div class='form-group'>
      <%= f.label :album_name %>
      <%= f.select :album_name, [], {}, id: :album_name %>
    </div>
  </div>

  <div class='col-3'>
    <div class='form-group'>
      <%= f.label :label_name %>
      <%= f.select :label_name, [], {}, id: :label_name %>
    </div>
  </div>
</div>
<div class='form-row'>
  <%= f.submit 'Add Song to Playlist', class: 'btn btn-info'%>
</div>
<% end %>

app/views/playlists/_form.html.erb
<div class="row">
  <% if playlist.errors.any? %>
  <h4>The following errors prevented the playlist from saving:</h4>
  <% playlist.errors.full_messages.each do |message| %>
  <div class="col-sm-12">
    <p class="bg-danger text-center">
      <%= message %>
    </p>
  </div>
  <% end %>
  <% end %>
</div>

<div class="row">
  <div class="col-sm-12">
    <%= form_with(model: playlist, local: true) do |f| %>
    <div class='form-group'>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>

    <div class='form-group'>
      <%= f.label :played_at %>
      <%= f.datetime_field :played_at, class: 'form-control' %>
    </div>

    <%= f.submit nil, class: 'btn btn-primary' %>

    <% end %>
  </div>
</div>

app/views/playlists/_playlist.html.erb
<div class="card">
  <div class="card-body">
    <%= link_to playlist.name, playlist %>
  </div>
  <div class="card-footer text-right">
    <small class="text-muted">by
      <%= link_to playlist.user.username, show_user_path(username: playlist.user.username) %>
      on <%= playlist.played_at %>
    </small>
  </div>
</div>

app/views/playlists/_playlist_songs_table.html.erb
<table class='table table-striped'>
  <tr>
    <th>Artist</th><th>Song</th><th>Album</th><th>Label</th><th>Actions</th>
  </tr>
<% playlist.songs.includes(:artist, album: [:label]).each do |song| %>
<tr>
  <td>
    <%= link_to song.artist.name, artist_path(song.artist) %>
  </td>
  <td>
    <%= link_to song.name, song_path(song) %>
  </td>
  <td>
    <%= link_to song.album.name, album_path(song.album) %>
  </td>
  <td>
    <% if song.album.label %>
    <%= link_to song.album.label.name, song.album.label %>
    <% end %>
  </td>
  <td>
    <% if playlist.user == current_user %>
    <%= render 'playlist_songs/actions', playlist_song: song.playlist_songs.find_by(playlist: playlist) %>
    <% end %>
  </td>
</tr>
<% end %>
</table>

app/views/playlists/edit.html.erb
<%= content_for :heading, @playlist.name %>

<%= render 'form', playlist: @playlist %>

app/views/playlists/index.html.erb
<% content_for :heading, "All Playlists" %>
<% content_for :sub_heading do %>
  <%= link_to 'New Playlist', new_playlist_path, class: 'btn btn-primary' %>
<% end %>

<div class="card-columns">
  <%= render @playlists %>
</div>

<%= paginate @playlists %>

app/views/playlists/new.html.erb
<% content_for :heading, "New Playlist" %>

<%= render 'form', playlist: @playlist %>

app/views/playlists/show.html.erb
<% content_for :heading, @playlist.name %>
<% content_for :sub_heading do %>
  <h5>
    by <%= link_to @playlist.user.username, show_user_path(username: @playlist.user.username) %>
    on <%= @playlist.played_at %>
  </h5>
  <% if @playlist.user == current_user %>
    <%= link_to 'Edit', edit_playlist_path(@playlist), class: 'btn btn-warning' %>
  <% end %>
<% end %>

<div id='playlist-songs-table-container' class='row' style='margin-top: 30px;'>
  <%= render 'playlist_songs_table', playlist: @playlist %>
</div>

<% if can?(:update, @playlist) && @playlist.in_progress? %>
  <%= render 'add_track_form', playlist: @playlist if @playlist.user == current_user %>
  <% confirm_message = 'Are you sure you would like to end this playlist? (You will not be able to add songs afterwords)' %>
  <%= link_to "End Playlist", end_playlist_path(@playlist),
                              method: :patch,
                              confirm: confirm_message,
                              class: 'btn btn-danger' %>
<% end %>

app/views/playlists/update_table.js.erb
$('#playlist-songs-table-container').html('<%= j render "playlists/playlist_songs_table", playlist: @playlist_song.playlist %>');