config/routes.rb
Rails.application.routes.draw do
  # Users
  devise_for :users
  get 'users/:username' => 'users#show', as: 'show_user'

  # Playlists
  resources :playlists do
    member do
      patch 'end'
      post 'add_track'
    end
  end

  resources :playlist_songs, only: [:destroy] do
    member do
      patch 'move_higher'
      patch 'move_lower'
    end
  end
  resources :songs, only: [:show]
  resources :artists, only: [:index, :show]
  resources :albums, only: [:index, :show]
  resources :labels, only: [:index, :show]

  root 'playlists#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Playlister</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <nav class='navbar navbar-dark bg-dark'>
    <div class='container'>
      <%= link_to 'Playlists', playlists_path, class: 'navbar-brand' %>
      <%= link_to 'Artists', artists_path, class: 'navbar-brand' %>
      <%= link_to 'Albums', albums_path, class: 'navbar-brand' %>
      <%= link_to 'Labels', labels_path, class: 'navbar-brand' %>
      <div class='pull-right'>
      <% if user_signed_in? %>
        <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: 'navbar-brand' %>
      <% else %>
        <%= link_to "Sign In", new_user_session_path, class: 'navbar-brand', style: "margin-right: 1px;" %> ●
        <%= link_to "Sign Up", new_user_registration_path, class: 'navbar-brand' %>
      <% end %>
      </div>
    </div>
  </nav>

  <div class="container-responsive">
    <div class="jumbotron">
      <% flash.each do |level, message| %>
        <p class='bg-<%= level %> text-center'>
          <%= message %>
        </p>
      <% end %>
      <div class="container">
        <h1><%= yield :heading %></h1>
        <%= yield :sub_heading %>
      </div>
    </div>
  </div>

  <div class='container'>
    <%= yield %>
  </div>
</body>
</html>